In [1]:
#1. Import the NUMPY package under the name np.


#2. Print the NUMPY version and the configuration.



#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?



#4. Print a.



#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"



#6. Print b.



#7. Do a and b have the same size? How do you prove that in Python code?




#8. Are you able to add a and b? Why or why not?



#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".



#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?



#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.




#12. Multiply a and c. Assign the result to e.



#13. Does e equal to a? Why or why not?




#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"




#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.




#"""
##16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.
#"""
#
#
#
#"""
##17. Print d and f. Do you have your expected f?
#For instance, if your d is:
#array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
#        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
#        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
#
#       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
#        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
#        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
#
#Your f should be:
#array([[[ 75.,  75.,  75.,  25.,  75.],
#        [ 75.,  75.,  25.,  25.,  25.],
#        [ 75.,  25.,  75.,  75.,  75.]],
#
#       [[ 25.,  25.,  25.,  25., 100.],
#        [ 75.,  75.,  75.,  75.,  75.],
#        [ 25.,  75.,   0.,  75.,  75.]]])
#"""
#
#
#"""
##18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
#array([[[ 'D',  'D',  'D',  'B',  'D'],
#        [ 'D',  'D',  'B',  'B',  'B'],
#        [ 'D',  'B',  'D',  'D',  'D']],
#
#       [[ 'B',  'B',  'B',  'B',  'E'],
#        [ 'D',  'D',  'D',  'D',  'D'],
#        [ 'B',  'D',   'A',  'D', 'D']]])
#Again, you don't need Numpy in this question.
#"""

In [2]:
#1. Import the NUMPY package under the name np.

import numpy as np



In [3]:
#2. Print the NUMPY version and the configuration.

print("NUMPY Version:",np.__version__, "\n")
print(np.show_config())



NUMPY Version: 1.17.4 

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/aswegs/opt/miniconda3/envs/code_red/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/aswegs/opt/miniconda3/envs/code_red/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/aswegs/opt/miniconda3/envs/code_red/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/aswegs/opt/miniconda3/envs/code_red/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/aswegs/opt/miniconda3/envs/code_red/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/aswegs/opt/miniconda3/envs/code_red/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/aswegs/opt/miniconda3/envs/code_red/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', N

In [4]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random_sample((2,3,5))



In [5]:
#4. Print a.

print(a)


[[[0.61977576 0.69480451 0.10347195 0.98417943 0.84442272]
  [0.59752709 0.09563547 0.80611655 0.28061155 0.23948116]
  [0.39551227 0.48768629 0.34856011 0.81278142 0.75163772]]

 [[0.45634727 0.81530459 0.63468105 0.10926964 0.26109678]
  [0.56444721 0.5976192  0.47289313 0.29651958 0.21874467]
  [0.3055442  0.40365255 0.65249793 0.37914938 0.57673228]]]


In [6]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5,2,3))



In [7]:
#6. Print b.

print(b)




[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [11]:
#7. Do a and b have the same size? How do you prove that in Python code?

print(a.shape)
print(b.shape)
print(a.shape == b.shape)



(2, 3, 5)
(5, 2, 3)
False


In [12]:
#8. Are you able to add a and b? Why or why not?

c = a + b
print(c)

# ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [13]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = np.transpose(b)

print(c)

print(c.shape)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(3, 2, 5)


In [14]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

print(a.shape)
print(c.shape)

c = np.ones((2,3,5))

print(c.shape)


(2, 3, 5)
(3, 2, 5)
(2, 3, 5)


In [15]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

d = a + c
print(d)




[[[1.61977576 1.69480451 1.10347195 1.98417943 1.84442272]
  [1.59752709 1.09563547 1.80611655 1.28061155 1.23948116]
  [1.39551227 1.48768629 1.34856011 1.81278142 1.75163772]]

 [[1.45634727 1.81530459 1.63468105 1.10926964 1.26109678]
  [1.56444721 1.5976192  1.47289313 1.29651958 1.21874467]
  [1.3055442  1.40365255 1.65249793 1.37914938 1.57673228]]]


In [16]:
#12. Multiply a and c. Assign the result to e.

e = a * c

print(e)



[[[0.61977576 0.69480451 0.10347195 0.98417943 0.84442272]
  [0.59752709 0.09563547 0.80611655 0.28061155 0.23948116]
  [0.39551227 0.48768629 0.34856011 0.81278142 0.75163772]]

 [[0.45634727 0.81530459 0.63468105 0.10926964 0.26109678]
  [0.56444721 0.5976192  0.47289313 0.29651958 0.21874467]
  [0.3055442  0.40365255 0.65249793 0.37914938 0.57673228]]]


In [17]:
#13. Does e equal to a? Why or why not?

print ( e == a)



[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [18]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)

print(d_max,d_min,d_mean)




1.9841794323533497 1.0956354657138894 1.493556782108571


In [22]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

print(np.empty((2,3,5)))

f = np.empty((2,3,5))






[[[0.61977576 0.69480451 0.10347195 0.98417943 0.84442272]
  [0.59752709 0.09563547 0.80611655 0.28061155 0.23948116]
  [0.39551227 0.48768629 0.34856011 0.81278142 0.75163772]]

 [[0.45634727 0.81530459 0.63468105 0.10926964 0.26109678]
  [0.56444721 0.5976192  0.47289313 0.29651958 0.21874467]
  [0.3055442  0.40365255 0.65249793 0.37914938 0.57673228]]]


In [26]:
# #16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
# If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
# If a value equals to d_mean, assign 50 to the corresponding value in f.
# Assign 0 to the corresponding value(s) in f for d_min in d.
# Assign 100 to the corresponding value(s) in f for d_max in d.
# In the end, f should have only the following values: 0, 25, 50, 75, and 100.
# Note: you don't have to use Numpy in this question.
print(f)
print(f[1,0,0])

for i, j, k in f:
    if f[i,j,k] == d_max:
        f[i,j,k] = 100
    elif f[i,j,k] > d_mean:
        f[i,j,k] = 75
    elif f[i,j,k] == d_mean:
        f[i,j,k] = 50
    elif f[i,j,k] > d_min:
        f[i,j,k] = 25
    else:
        f[i,j,k] = 0




[[[0.61977576 0.69480451 0.10347195 0.98417943 0.84442272]
  [0.59752709 0.09563547 0.80611655 0.28061155 0.23948116]
  [0.39551227 0.48768629 0.34856011 0.81278142 0.75163772]]

 [[0.45634727 0.81530459 0.63468105 0.10926964 0.26109678]
  [0.56444721 0.5976192  0.47289313 0.29651958 0.21874467]
  [0.3055442  0.40365255 0.65249793 0.37914938 0.57673228]]]
0.4563472713281609


IndexError: arrays used as indices must be of integer (or boolean) type

In [34]:
variable = 0
print(f[int("{}".format(variable)),2,2])


0.3485601099660671


In [31]:
print(f[0,2,2])


0.3485601099660671


In [ ]:
##17. Print d and f. Do you have your expected f?
#For instance, if your d is:
#array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
#        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
#        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
#
#       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
#        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
#        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
#
#Your f should be:
#array([[[ 75.,  75.,  75.,  25.,  75.],
#        [ 75.,  75.,  25.,  25.,  25.],
#        [ 75.,  25.,  75.,  75.,  75.]],
#
#       [[ 25.,  25.,  25.,  25., 100.],
#        [ 75.,  75.,  75.,  75.,  75.],
#        [ 25.,  75.,   0.,  75.,  75.]]])





In [ ]:
##18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
#array([[[ 'D',  'D',  'D',  'B',  'D'],
#        [ 'D',  'D',  'B',  'B',  'B'],
#        [ 'D',  'B',  'D',  'D',  'D']],
#
#       [[ 'B',  'B',  'B',  'B',  'E'],
#        [ 'D',  'D',  'D',  'D',  'D'],
#        [ 'B',  'D',   'A',  'D', 'D']]])
#Again, you don't need Numpy in this question.




