In [2]:
import numpy as np
import pandas as pd

In [9]:
df = np.random.random_sample((10,5))

In [10]:
print(df)

[[0.2429535  0.78550101 0.63348256 0.26791219 0.01339607]
 [0.30641019 0.26953104 0.77947949 0.32327818 0.76610856]
 [0.20745113 0.10666977 0.21188968 0.88319585 0.15562489]
 [0.40313907 0.25323301 0.81567522 0.00755388 0.59959121]
 [0.14069445 0.59103879 0.49198189 0.34973823 0.68095884]
 [0.96624139 0.72551199 0.42766203 0.68269376 0.05971822]
 [0.01534708 0.86904727 0.43177317 0.40307022 0.31522623]
 [0.62160916 0.82853894 0.43544577 0.03797694 0.07599976]
 [0.43567532 0.14036415 0.55765307 0.02597289 0.92499086]
 [0.12783386 0.32029066 0.21879541 0.1747591  0.69251751]]


In [11]:
df = pd.DataFrame(df)

In [13]:
df.columns = ["banana_density","banana_mass","apple_density","apple_mass","mango_mass"]

In [14]:
df

banana_density  banana_mass  apple_density  apple_mass  mango_mass
0        0.242953     0.785501       0.633483    0.267912    0.013396
1        0.306410     0.269531       0.779479    0.323278    0.766109
2        0.207451     0.106670       0.211890    0.883196    0.155625
3        0.403139     0.253233       0.815675    0.007554    0.599591
4        0.140694     0.591039       0.491982    0.349738    0.680959
5        0.966241     0.725512       0.427662    0.682694    0.059718
6        0.015347     0.869047       0.431773    0.403070    0.315226
7        0.621609     0.828539       0.435446    0.037977    0.076000
8        0.435675     0.140364       0.557653    0.025973    0.924991
9        0.127834     0.320291       0.218795    0.174759    0.692518

In [15]:
new_col = {"mango density": np.random.random_sample((10,0))}

In [16]:
print(new_col)

{'mango density': array([], shape=(10, 0), dtype=float64)}


In [17]:
df.drop(columns="mango_mass")

banana_density  banana_mass  apple_density  apple_mass
0        0.242953     0.785501       0.633483    0.267912
1        0.306410     0.269531       0.779479    0.323278
2        0.207451     0.106670       0.211890    0.883196
3        0.403139     0.253233       0.815675    0.007554
4        0.140694     0.591039       0.491982    0.349738
5        0.966241     0.725512       0.427662    0.682694
6        0.015347     0.869047       0.431773    0.403070
7        0.621609     0.828539       0.435446    0.037977
8        0.435675     0.140364       0.557653    0.025973
9        0.127834     0.320291       0.218795    0.174759

## Subsetting

In [20]:
df.loc[df["banana_density"].lt(.5) | df["apple_density"].lt(.5), ["banana_density", "apple_density"]]

banana_density
0        0.242953
1        0.306410
2        0.207451
3        0.403139
4        0.140694
5        0.966241
6        0.015347
7        0.621609
8        0.435675
9        0.127834

In [22]:
df.loc[df["banana_density"].lt(.5) & df["apple_density"].lt(.5), ["banana_density", "apple_density"]]

banana_density  apple_density
2        0.207451       0.211890
4        0.140694       0.491982
6        0.015347       0.431773
9        0.127834       0.218795

In [25]:
df.iloc[6,[0,2]]

banana_density    0.015347
apple_density     0.431773
Name: 6, dtype: float64

In [33]:
(df.iloc[6,[0,2]]
.to_frame()
.transpose())

banana_density  apple_density
6        0.015347       0.431773